param(
    [ValidateSet("impact", "tics", "status-only", "sample-analysis")]
    [string]$Session = "impact",

    [string]$DosboxExe = "C:\ARL\DOSBox-X-ARL\dosbox-x-arl.exe",
    [string]$ArlRoot = "C:\ARL",
    [string]$ImplusPath = "C:\ARL\IMPLUS",
    [string]$ComPort = "COM5",
    [int]$RxDelay = 1000,
    [int]$Cycles = 12000,
    [int]$HangMs = 15000,
    [string]$RunRoot = "C:\ARL\diagnostics",
    [switch]$Wait,
    [switch]$NoLaunch
)

$ErrorActionPreference = "Stop"

function Join-ArlPath([string]$Base, [string]$Child) {
    if ($Base -match '^[A-Za-z]:') {
        return "$($Base.TrimEnd([char[]]'\/'))\$Child"
    }
    return Join-Path $Base $Child
}

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$runDir = Join-ArlPath $RunRoot "$Session-$stamp"
New-Item -ItemType Directory -Force -Path $runDir | Out-Null

$tracePath = Join-ArlPath $runDir "serial.ndjson"
$logPath = Join-ArlPath $runDir "dosbox.log"
$confPath = Join-ArlPath $runDir "dosbox-$Session.conf"
$lptPath = Join-ArlPath $runDir "LPTCAP.PRN"
$interfacPath = Join-ArlPath $ImplusPath "INTERFAC.DAT"

switch ($Session) {
    "tics" {
        $autoexecCommand = "tics"
    }
    "status-only" {
        $autoexecCommand = "ARLTRACE STATUS"
    }
    default {
        $autoexecCommand = "implus"
    }
}

$conf = @"
# Generated by Start-ArlTraceRun.ps1
# Run directory: $runDir

[sdl]
fullscreen = false
autolock = false

[dosbox]
machine = svga_s3
captures = $runDir
memsize = 16
logfile = $logPath

[cpu]
core = normal
cputype = 486
cycles = fixed $Cycles

[serial]
serial1 = directserial realport:$ComPort rxdelay:$RxDelay arltracelevel:full arltracesession:$Session arltracehangms:$HangMs arltrace:$tracePath
serial2 = disabled
serial3 = disabled
serial4 = disabled

[parallel]
parallel1 = file append:$lptPath timeout:2000
parallel2 = disabled

[dos]
xms = true
ems = true
umb = true

[autoexec]
mount c "$ImplusPath"
c:
DOS\MOUSE.COM
$autoexecCommand
"@

$conf | Set-Content -Path $confPath -Encoding ASCII

$metadata = [pscustomobject]@{
    session = $Session
    created = (Get-Date).ToString("o")
    run_dir = $runDir
    dosbox_exe = $DosboxExe
    config = $confPath
    trace = $tracePath
    log = $logPath
    interfac_dat = $interfacPath
    com_port = $ComPort
    rxdelay = $RxDelay
    cycles = $Cycles
    hang_ms = $HangMs
}
$metadata | ConvertTo-Json -Depth 5 | Set-Content -Path (Join-ArlPath $runDir "run-metadata.json") -Encoding UTF8

Write-Host "Run directory: $runDir"
Write-Host "Config: $confPath"
Write-Host "Trace: $tracePath"
Write-Host "Log: $logPath"

if ($NoLaunch) {
    Write-Host "NoLaunch set; DOSBox-X was not started."
    exit 0
}

if (-not (Test-Path -Path $DosboxExe -PathType Leaf)) {
    throw "DOSBox-X ARL executable not found: $DosboxExe"
}

$process = Start-Process -FilePath $DosboxExe -ArgumentList @("-conf", $confPath) -PassThru
Write-Host "Started DOSBox-X ARL PID $($process.Id)"

if ($Wait) {
    $process.WaitForExit()
    if (Test-Path -Path $interfacPath -PathType Leaf) {
        Copy-Item -Path $interfacPath -Destination (Join-ArlPath $runDir "INTERFAC.DAT.after") -Force
    }
    Write-Host "DOSBox-X exited with code $($process.ExitCode)"
}
