param(
    [ValidateSet("impact", "tics", "status-only", "sample-analysis", "impact-emulator", "tics-emulator")]
    [string]$Session = "impact",

    [string]$DosboxExe = "C:\ARL\DOSBox-X-ARL\dosbox-x-arl.exe",
    [string]$ArlRoot = "C:\ARL",
    [string]$ImplusPath = "C:\ARL\IMPLUS",
    [string]$ComPort = "COM5",
    [string]$EmulatorHost = "127.0.0.1",
    [int]$EmulatorPort = 3460,
    [ValidateSet("happy-path", "silent-after-spark", "delayed-result", "line-drop", "bad-response")]
    [string]$EmulatorMode = "happy-path",
    [string]$EmulatorProfilePath = (Join-Path $PSScriptRoot "profiles\arl3460-baseline.json"),
    [int]$RxDelay = 1000,
    [int]$Cycles = 12000,
    [ValidateSet("basic", "uartdata", "uart", "full")]
    [string]$TraceLevel = "basic",
    [int]$HangMs = 15000,
    [string]$RunRoot = "C:\ARL\diagnostics",
    [switch]$Wait,
    [switch]$NoLaunch
)

$ErrorActionPreference = "Stop"

function Join-ArlPath([string]$Base, [string]$Child) {
    if ($Base -match '^[A-Za-z]:') {
        return "$($Base.TrimEnd([char[]]'\/'))\$Child"
    }
    return Join-Path $Base $Child
}

$stamp = Get-Date -Format "yyyyMMdd-HHmmss"
$runDir = Join-ArlPath $RunRoot "$Session-$stamp"
New-Item -ItemType Directory -Force -Path $runDir | Out-Null

$tracePath = Join-ArlPath $runDir "serial.ndjson"
$emulatorTracePath = Join-ArlPath $runDir "emulator.ndjson"
$logPath = Join-ArlPath $runDir "dosbox.log"
$confPath = Join-ArlPath $runDir "dosbox-$Session.conf"
$lptPath = Join-ArlPath $runDir "LPTCAP.PRN"
$interfacPath = Join-ArlPath $ImplusPath "INTERFAC.DAT"
$usesEmulator = $Session -eq "impact-emulator" -or $Session -eq "tics-emulator"
$usesTics = $Session -eq "tics" -or $Session -eq "tics-emulator"

if ($usesTics) {
    New-Item -ItemType Directory -Force -Path (Join-ArlPath $ImplusPath "TICS\PROC") | Out-Null

    foreach ($extension in @("DBI", "TXT", "HLP")) {
        $source = Join-ArlPath $ImplusPath "TICS\DBTICSOE.$extension"
        $target = Join-ArlPath $ImplusPath "TICS\DBTICS.$extension"
        if ((Test-Path -Path $source -PathType Leaf) -and -not (Test-Path -Path $target -PathType Leaf)) {
            Copy-Item -Path $source -Destination $target
        }
    }
}

switch ($Session) {
    { $_ -eq "tics" -or $_ -eq "tics-emulator" } {
        $autoexecCommand = @"
if exist TICS\TICS.EXE cd TICS
TICS
"@
    }
    "status-only" {
        $autoexecCommand = "ARLTRACE STATUS"
    }
    default {
        $autoexecCommand = "implus"
    }
}

if ($usesEmulator) {
    $serialLine = "serial1 = nullmodem server:$EmulatorHost port:$EmulatorPort transparent:1 rxdelay:$RxDelay"
    $serialComment = "# Emulator session: nullmodem over localhost. This never opens $ComPort."
} else {
    $serialLine = "serial1 = directserial realport:$ComPort rxdelay:$RxDelay arltracelevel:$TraceLevel arltracesession:$Session arltracehangms:$HangMs arltrace:$tracePath"
    $serialComment = "# Direct ARL session: opens the real Windows serial port."
}

$emulatorScriptPath = Join-ArlPath $PSScriptRoot "Start-ArlEmulator.ps1"
$emulatorCommand = "pwsh -NoProfile -File `"$emulatorScriptPath`" -Mode $EmulatorMode -ProfilePath `"$EmulatorProfilePath`" -ListenAddress $EmulatorHost -Port $EmulatorPort -Session $Session -LogPath `"$emulatorTracePath`""

$conf = @"
# Generated by Start-ArlTraceRun.ps1
# Run directory: $runDir

[sdl]
fullscreen = false
autolock = false

[dosbox]
machine = svga_s3
captures = $runDir
memsize = 16
logfile = $logPath

[cpu]
core = normal
cputype = 486
cycles = fixed $Cycles

[serial]
$serialComment
$serialLine
serial2 = disabled
serial3 = disabled
serial4 = disabled

[parallel]
parallel1 = file append:$lptPath timeout:2000
parallel2 = disabled

[dos]
xms = true
ems = true
umb = true

[autoexec]
mount c "$ImplusPath"
c:
DOS\MOUSE.COM
$autoexecCommand
"@

$conf | Set-Content -Path $confPath -Encoding ASCII

$metadata = [pscustomobject]@{
    session = $Session
    created = (Get-Date).ToString("o")
    run_dir = $runDir
    dosbox_exe = $DosboxExe
    config = $confPath
    trace = if ($usesEmulator) { $null } else { $tracePath }
    emulator_trace = if ($usesEmulator) { $emulatorTracePath } else { $null }
    log = $logPath
    interfac_dat = $interfacPath
    com_port = $ComPort
    serial_backend = if ($usesEmulator) { "nullmodem-emulator" } else { "directserial" }
    emulator_host = if ($usesEmulator) { $EmulatorHost } else { $null }
    emulator_port = if ($usesEmulator) { $EmulatorPort } else { $null }
    emulator_mode = if ($usesEmulator) { $EmulatorMode } else { $null }
    emulator_profile = if ($usesEmulator) { $EmulatorProfilePath } else { $null }
    emulator_command = if ($usesEmulator) { $emulatorCommand } else { $null }
    rxdelay = $RxDelay
    cycles = $Cycles
    trace_level = if ($usesEmulator) { $null } else { $TraceLevel }
    hang_ms = $HangMs
}
$metadata | ConvertTo-Json -Depth 5 | Set-Content -Path (Join-ArlPath $runDir "run-metadata.json") -Encoding UTF8

Write-Host "Run directory: $runDir"
Write-Host "Config: $confPath"
if ($usesEmulator) {
    Write-Host "Emulator trace: $emulatorTracePath"
    Write-Host "Start emulator first:"
    Write-Host $emulatorCommand
} else {
    Write-Host "Trace: $tracePath"
}
Write-Host "Log: $logPath"

if ($NoLaunch) {
    Write-Host "NoLaunch set; DOSBox-X was not started."
    exit 0
}

if (-not (Test-Path -Path $DosboxExe -PathType Leaf)) {
    throw "DOSBox-X ARL executable not found: $DosboxExe"
}

$process = Start-Process -FilePath $DosboxExe -ArgumentList @("-conf", $confPath) -PassThru
Write-Host "Started DOSBox-X ARL PID $($process.Id)"

if ($Wait) {
    $process.WaitForExit()
    if (Test-Path -Path $interfacPath -PathType Leaf) {
        Copy-Item -Path $interfacPath -Destination (Join-ArlPath $runDir "INTERFAC.DAT.after") -Force
    }
    Write-Host "DOSBox-X exited with code $($process.ExitCode)"
}
